/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#003d9b",
        "primary-container": "#0052cc",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "secondary": "#006c47",
        "secondary-container": "#82f9be",
        "secondary-fixed": "#82f9be",
        "secondary-fixed-dim": "#65dca4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00734c",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005235",
        "tertiary": "#394456",
        "tertiary-container": "#505c6f",
        "tertiary-fixed": "#d7e3fa",
        "tertiary-fixed-dim": "#bbc7dd",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c8d4ea",
        "on-tertiary-fixed": "#101c2c",
        "on-tertiary-fixed-variant": "#3c4759",
        "surface": "#f9f9ff",
        "surface-dim": "#cadaff",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e8edff",
        "surface-container-high": "#e0e8ff",
        "surface-container-highest": "#d7e2ff",
        "surface-variant": "#d7e2ff",
        "surface-tint": "#0c56d0",
        "on-surface": "#041b3c",
        "on-surface-variant": "#434654",
        "on-background": "#041b3c",
        "background": "#f9f9ff",
        "outline": "#737685",
        "outline-variant": "#c3c6d6",
        "inverse-surface": "#1d3052",
        "inverse-on-surface": "#edf0ff",
        "inverse-primary": "#b2c5ff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(4, 27, 60, 0.06)",
        card: "0 4px 16px rgba(4, 27, 60, 0.08)",
      },
    },
  },
  plugins: [],
};
